kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: app-data-pvc-sc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard # Notice this value
  resources:
    requests:
      storage: 512Mi
