apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pod-with-pvc
  name: pod-with-pvc
spec:
  volumes:
    - name: app-data
      persistentVolumeClaim:
        claimName: app-data-pvc
  containers:
    - args:
        - /bin/sh
        - -c
        - sleep infinity
      image: busybox:1.37.0
      name: pod-with-pvc
      resources: {}
      volumeMounts:
        - mountPath: "/app/data"
          name: app-data
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
