apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: annotated-pod
  annotations:
    description: This is a web server
  name: annotated-pod
spec:
  containers:
  - image: httpd:2.4.63
    name: annotated-pod
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
