apiVersion: batch/v1
kind: CronJob
metadata:
  creationTimestamp: null
  name: soft-work
spec:
  jobTemplate:
    metadata:
      creationTimestamp: null
      name: soft-work
    spec:
      template:
        metadata:
          creationTimestamp: null
        spec:
          containers:
            - command:
                - /bin/sh
                - -c
                - echo "Start Work..."; sleep 10; echo "Done"
              image: busybox:1.37.0
              name: soft-work
              resources: {}
          restartPolicy: OnFailure
  schedule: "* * * * *"
  successfulJobsHistoryLimit: 6
  failedJobsHistoryLimit: 3
status: {}
