apiVersion: v1
kind: Pod
metadata:
  name: httpd
  labels:
    app: webserver
    profile: prod
spec:
  containers:
    - name: httpd
      image: httpd:2.4.63
      env:
        - name: APP_DOMAIN
          value: lemoncode.net
      ports:
        - containerPort: 80
