apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: uptime
  name: uptime
spec:
  containers:
    - command:
        - /bin/sh
      args:
        - -c
        - |
          while true; do
            echo "Still alive: $(uptime -s)"
            sleep 5
          done
      image: busybox:1.36.1
      name: uptime
      resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
