apiVersion: v1
kind: Pod
metadata:
  name: stress-d
  namespace: stress-demo
spec:
  containers:
  - image: jaimesalas/ckad-guide:stress-v0.0.1
    name: consumer
    args: [/bin/sh, -c, 'stress --vm 1 --vm-bytes $(shuf -i 10-240 -n 1)M --vm-hang 1']
    resources:
      limits:
        memory: "250Mi"
      requests:
        memory: "250Mi"